SELECT DISTINCT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME LIKE '%tv%' 

;

SELECT DISTINCT TABLE_SCHEMA, TABLE_NAME as TV_table
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME LIKE '%tv%' 
;